### ISSUE TITLE
Example how to use readOpmlFile

### ISSUE THREAD

**Issue by frankmeeuwsen** [scripting/opml#1]
Hi

I'm just starting to get more in Node.JS. A small project I want to do is read an OPML file for my own feeds from pinboard and starred/tagged Inoreader items. Next I want to check per feed in the OPML file if there is something new I starred or liked for further processing. 

I try to use your repository to read the OPML file with readOPML but I constantly get an error message with my OPML subs in it. I have no idea how to move forward. 

You can find the code on https://github.com/frankmeeuwsen/pinboard/blob/master/test.js and the OPML file in [my repo](https://raw.githubusercontent.com/frankmeeuwsen/pinboard/master/data/feeds.opml)

If you could help me out with a small step forward to make sure I can succesfully read the OPML file, that would be great.

**Comment by scripting** [comment]
The callback from readOpmlFile takes one param, the JavaScript structure it
got from parsing the file.

it there was an error it is undefined.

I just added some example code to my project to illustrate.

https://github.com/scripting/opml/blob/master/examples/readfile/read.js

Dave

**Comment by frankmeeuwsen** [comment]
That explains it. I have it working now. Thanks for the quick follow-up!
